# Python Fundamentals

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path
import sys

### Experiencing with numpy

In [2]:
a = np.array([1,2,3,4])
b = np.array([4,16,64,256,1249])

print(b.mean())

print([x**2 for x in a])
print(np.array([x**2 for x in a]))

print(a ** 2)

print(np.sqrt(b))

317.8
[np.int64(1), np.int64(4), np.int64(9), np.int64(16)]
[ 1  4  9 16]
[ 1  4  9 16]
[ 2.          4.          8.         16.         35.34119409]


In [3]:

# Create dummy dataframe
data = {
    "cateGOrY": ["A", "b   ", "a", "     b", "C   ", "   A", "C", "B   ", "A", "C"],
    "Col vAlUe": ["12", "15", " 12€", "18", "25  $", "$ 44", "22", 19, 11, "$28"],
    "date": pd.date_range(start="2025-08-01", periods=10, freq="D").astype(str)  # string, not datetime
}

df_raw = pd.DataFrame(data)
df_raw


cateGOrY Col vAlUe        date
0        A        12  2025-08-01
1     b           15  2025-08-02
2        a       12€  2025-08-03
3        b        18  2025-08-04
4     C        25  $  2025-08-05
5        A      $ 44  2025-08-06
6        C        22  2025-08-07
7     B           19  2025-08-08
8        A        11  2025-08-09
9        C       $28  2025-08-10

In [4]:
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   cateGOrY   10 non-null     object
 1   Col vAlUe  10 non-null     object
 2   date       10 non-null     object
dtypes: object(3)
memory usage: 368.0+ bytes


In [5]:
df_raw.describe()

cateGOrY Col vAlUe        date
count        10        10          10
unique        8        10          10
top           A        12  2025-08-01
freq          2         1           1

In [6]:

PROJECT_ROOT = Path.cwd().parent

sys.path.append(str(PROJECT_ROOT))

from src.utils import *

df_date = parse_date(df_raw, 'date')

df_cleaned = clean_columns(df_date)

display(df_raw.head())
display(df_raw.info())
display(df_cleaned.head())
display(df_cleaned.info())

C:\bootcamp_damien_rupp\project\src\utils.py:24: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")
C:\bootcamp_damien_rupp\project\src\utils.py:24: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")
C:\bootcamp_damien_rupp\project\src\utils.py:24: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df[col] = pd.to_numeric(df[col], errors="ignore")


cateGOrY Col vAlUe        date
0        A        12  2025-08-01
1     b           15  2025-08-02
2        a       12€  2025-08-03
3        b        18  2025-08-04
4     C        25  $  2025-08-05

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   cateGOrY   10 non-null     object
 1   Col vAlUe  10 non-null     object
 2   date       10 non-null     object
dtypes: object(3)
memory usage: 368.0+ bytes


None

category  col_value        date
0        a         12  2025-08-01
1        b         15  2025-08-02
2        a         12  2025-08-03
3        b         18  2025-08-04
4        c         25  2025-08-05

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   category   10 non-null     object
 1   col_value  10 non-null     int64 
 2   date       10 non-null     object
dtypes: int64(1), object(2)
memory usage: 368.0+ bytes


None